UNIVERSE = ['SOUTHEROS', 'PANDEMONIUM']
KINGDOMS_EMBLEM = {'SPACE': 'GORILLA', 'LAND': 'PANDA', 'WATER': 'OCTOPUS', 'ICE': 'MAMMOTH', 'AIR': 'OWL',
                   'FIRE': 'DRAGON'}
MIN_NO_OF_WINS = 3
